/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConstructionRouteImport } from './routes/construction'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings_.subscription'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects_.$projectId'
import { Route as ProjectsProjectIdConstructionRouteImport } from './routes/projects_.$projectId_.construction'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionRoute = ConstructionRouteImport.update({
  id: '/construction',
  path: '/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/settings_/subscription',
  path: '/settings/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects_/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdConstructionRoute =
  ProjectsProjectIdConstructionRouteImport.update({
    id: '/projects_/$projectId_/construction',
    path: '/projects/$projectId/construction',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/construction': typeof ConstructionRoute
  '/dashboard': typeof DashboardRoute
  '/executive': typeof ExecutiveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/projects/$projectId/construction': typeof ProjectsProjectIdConstructionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/construction': typeof ConstructionRoute
  '/dashboard': typeof DashboardRoute
  '/executive': typeof ExecutiveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/settings/subscription': typeof SettingsSubscriptionRoute
  '/projects/$projectId/construction': typeof ProjectsProjectIdConstructionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/construction': typeof ConstructionRoute
  '/dashboard': typeof DashboardRoute
  '/executive': typeof ExecutiveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/procurement': typeof ProcurementRoute
  '/projects': typeof ProjectsRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/projects_/$projectId': typeof ProjectsProjectIdRoute
  '/settings_/subscription': typeof SettingsSubscriptionRoute
  '/projects_/$projectId_/construction': typeof ProjectsProjectIdConstructionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/construction'
    | '/dashboard'
    | '/executive'
    | '/login'
    | '/onboarding'
    | '/procurement'
    | '/projects'
    | '/register'
    | '/settings'
    | '/projects/$projectId'
    | '/settings/subscription'
    | '/projects/$projectId/construction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/construction'
    | '/dashboard'
    | '/executive'
    | '/login'
    | '/onboarding'
    | '/procurement'
    | '/projects'
    | '/register'
    | '/settings'
    | '/projects/$projectId'
    | '/settings/subscription'
    | '/projects/$projectId/construction'
  id:
    | '__root__'
    | '/'
    | '/construction'
    | '/dashboard'
    | '/executive'
    | '/login'
    | '/onboarding'
    | '/procurement'
    | '/projects'
    | '/register'
    | '/settings'
    | '/projects_/$projectId'
    | '/settings_/subscription'
    | '/projects_/$projectId_/construction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstructionRoute: typeof ConstructionRoute
  DashboardRoute: typeof DashboardRoute
  ExecutiveRoute: typeof ExecutiveRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProcurementRoute: typeof ProcurementRoute
  ProjectsRoute: typeof ProjectsRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRoute
  ProjectsProjectIdConstructionRoute: typeof ProjectsProjectIdConstructionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction': {
      id: '/construction'
      path: '/construction'
      fullPath: '/construction'
      preLoaderRoute: typeof ConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/subscription': {
      id: '/settings_/subscription'
      path: '/settings/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId': {
      id: '/projects_/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId_/construction': {
      id: '/projects_/$projectId_/construction'
      path: '/projects/$projectId/construction'
      fullPath: '/projects/$projectId/construction'
      preLoaderRoute: typeof ProjectsProjectIdConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstructionRoute: ConstructionRoute,
  DashboardRoute: DashboardRoute,
  ExecutiveRoute: ExecutiveRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProcurementRoute: ProcurementRoute,
  ProjectsRoute: ProjectsRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRoute,
  ProjectsProjectIdConstructionRoute: ProjectsProjectIdConstructionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
